// <auto-generated />
using System;
using InfraDesk.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InfraDesk.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260429035619_MegaSeedAndRefactoring")]
    partial class MegaSeedAndRefactoring
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InfraDesk.Core.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DynamicDataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("InventoryNumber")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("313f9b02-c081-47aa-84bc-74bc17b14782"),
                            AssetTypeId = new Guid("d8cd223f-b1e1-4d9f-8054-336f53d86b6a"),
                            CreatedAt = new DateTime(2026, 4, 29, 3, 56, 19, 594, DateTimeKind.Utc).AddTicks(663),
                            DynamicDataJson = "{\"CPU\": \"32 Cores\", \"RAM\": \"128GB\", \"OS\": \"Windows Server 2022\"}",
                            InventoryNumber = "INV-0001",
                            IsDeleted = false,
                            LocationId = new Guid("4c40e4fd-a669-4220-9d34-f7e2d4392fee"),
                            ManufacturerId = new Guid("8306d64d-a981-4cd3-8828-a4d7ace57d56"),
                            Name = "SRV-DC-01",
                            OwnerId = new Guid("027b9676-b1e9-42e2-b9d3-e315fea4e62f"),
                            SerialNumber = "DELL-12345",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("InfraDesk.Core.Entities.AssetType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IconKey")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AssetTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d8cd223f-b1e1-4d9f-8054-336f53d86b6a"),
                            CreatedAt = new DateTime(2026, 4, 29, 3, 56, 19, 594, DateTimeKind.Utc).AddTicks(647),
                            IconKey = "ServerIcon",
                            IsDeleted = false,
                            Name = "Server"
                        },
                        new
                        {
                            Id = new Guid("d3689eb8-0421-471b-a988-c8ca3ff84269"),
                            CreatedAt = new DateTime(2026, 4, 29, 3, 56, 19, 594, DateTimeKind.Utc).AddTicks(648),
                            IconKey = "LaptopIcon",
                            IsDeleted = false,
                            Name = "Laptop"
                        });
                });

            modelBuilder.Entity("InfraDesk.Core.Entities.License", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LicenseKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SoftwareId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SoftwareId");

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("InfraDesk.Core.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoomNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentLocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5ecf02f4-0985-447f-8049-b0e2609b7dd8"),
                            Address = "Musterstraße 1",
                            CreatedAt = new DateTime(2026, 4, 29, 3, 56, 19, 594, DateTimeKind.Utc).AddTicks(569),
                            IsDeleted = false,
                            Name = "Hauptsitz Berlin",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("4c40e4fd-a669-4220-9d34-f7e2d4392fee"),
                            CreatedAt = new DateTime(2026, 4, 29, 3, 56, 19, 594, DateTimeKind.Utc).AddTicks(571),
                            IsDeleted = false,
                            Name = "Serverraum 01",
                            ParentLocationId = new Guid("5ecf02f4-0985-447f-8049-b0e2609b7dd8"),
                            RoomNumber = "UG-01",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("InfraDesk.Core.Entities.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupportContact")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8306d64d-a981-4cd3-8828-a4d7ace57d56"),
                            CreatedAt = new DateTime(2026, 4, 29, 3, 56, 19, 594, DateTimeKind.Utc).AddTicks(632),
                            IsDeleted = false,
                            Name = "Dell Technologies"
                        });
                });

            modelBuilder.Entity("InfraDesk.Core.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("027b9676-b1e9-42e2-b9d3-e315fea4e62f"),
                            CreatedAt = new DateTime(2026, 4, 29, 3, 56, 19, 594, DateTimeKind.Utc).AddTicks(613),
                            Email = "m.admin@musterfirma.de",
                            FirstName = "Max",
                            IsDeleted = false,
                            LastName = "Admin",
                            TeamId = new Guid("6dc5d06e-6d71-4fe6-9bce-f439830d638b"),
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("InfraDesk.Core.Entities.Software", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Softwares");
                });

            modelBuilder.Entity("InfraDesk.Core.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6dc5d06e-6d71-4fe6-9bce-f439830d638b"),
                            CreatedAt = new DateTime(2026, 4, 29, 3, 56, 19, 594, DateTimeKind.Utc).AddTicks(594),
                            IsDeleted = false,
                            Name = "IT-Administration",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("InfraDesk.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Domain")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 4, 29, 3, 56, 19, 594, DateTimeKind.Utc).AddTicks(444),
                            Domain = "musterfirma.de",
                            IsDeleted = false,
                            Name = "Musterfirma GmbH"
                        });
                });

            modelBuilder.Entity("InfraDesk.Core.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedAssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAssetId");

                    b.HasIndex("RequesterId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a5f061b1-e6b4-429a-a7e4-c63be414297a"),
                            AssignedAssetId = new Guid("313f9b02-c081-47aa-84bc-74bc17b14782"),
                            CreatedAt = new DateTime(2026, 4, 29, 3, 56, 19, 594, DateTimeKind.Utc).AddTicks(682),
                            Description = "Der Server meldet einen defekten Sektor auf Disk 0.",
                            IsDeleted = false,
                            Priority = "High",
                            RequesterId = new Guid("027b9676-b1e9-42e2-b9d3-e315fea4e62f"),
                            Status = "Open",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Title = "Festplattentausch erforderlich"
                        });
                });

            modelBuilder.Entity("InfraDesk.Core.Entities.Asset", b =>
                {
                    b.HasOne("InfraDesk.Core.Entities.AssetType", "AssetType")
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfraDesk.Core.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("InfraDesk.Core.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.HasOne("InfraDesk.Core.Entities.Person", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.Navigation("AssetType");

                    b.Navigation("Location");

                    b.Navigation("Manufacturer");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("InfraDesk.Core.Entities.License", b =>
                {
                    b.HasOne("InfraDesk.Core.Entities.Software", "Software")
                        .WithMany()
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Software");
                });

            modelBuilder.Entity("InfraDesk.Core.Entities.Location", b =>
                {
                    b.HasOne("InfraDesk.Core.Entities.Location", "ParentLocation")
                        .WithMany()
                        .HasForeignKey("ParentLocationId");

                    b.Navigation("ParentLocation");
                });

            modelBuilder.Entity("InfraDesk.Core.Entities.Person", b =>
                {
                    b.HasOne("InfraDesk.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("InfraDesk.Core.Entities.Software", b =>
                {
                    b.HasOne("InfraDesk.Core.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("InfraDesk.Core.Entities.Team", b =>
                {
                    b.HasOne("InfraDesk.Core.Entities.Person", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("InfraDesk.Core.Entities.Ticket", b =>
                {
                    b.HasOne("InfraDesk.Core.Entities.Asset", "AssignedAsset")
                        .WithMany()
                        .HasForeignKey("AssignedAssetId");

                    b.HasOne("InfraDesk.Core.Entities.Person", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId");

                    b.Navigation("AssignedAsset");

                    b.Navigation("Requester");
                });
#pragma warning restore 612, 618
        }
    }
}
